### ISSUE TITLE
b站改版首页  显示不出来了

### ISSUE THREAD

**Issue by aen516954023** [chitosai/bili-guessYouLike#5]
b站改版首页  显示不出来了

**Comment by taseikyo** [comment]
新版改了好多属性，就显示不出来了 ;3

**Comment by chitosai** [comment]
今天终于灰度到我了。。
有空就修复！

**Comment by chitosai** [comment]
暂时弄了一下，先发布了版本大家可以试一下，有bug请反馈

因为新版本用了响应式的布局，细调样式可能花时间比较多，我暂时先把右边留空白了，比较难看
等我有空了我会精修一下的。。现在先暂时这样吧
