### ISSUE TITLE
又双叒叕显示不出来辣

### ISSUE THREAD

**Issue by taseikyo** [chitosai/bili-guessYouLike#7]
大概是 b 站更新首页结构了
![3373529288](https://user-images.githubusercontent.com/23132915/110109458-709aa600-7de8-11eb-9345-b607f8f0361b.jpg)

**Comment by chitosai** [comment]
能开个首页控制台截图给我看下么？我这边似乎是正常的

**Comment by taseikyo** [comment]
大概是这个？
![20210306113756](https://user-images.githubusercontent.com/23132915/110193702-78059200-7e70-11eb-8166-1816b6212a14.png)

**Comment by chitosai** [comment]
![image](https://user-images.githubusercontent.com/1511411/110195598-1e12b700-7df3-11eb-9d90-82e1a2a818b5.png)
虽然不知道发生了什么。。要不你点下这个清除缓存试试？

**Comment by taseikyo** [comment]
清理缓存后会显示，但是看了视频之后又没了😢

**Comment by chitosai** [comment]
emmm。。我自己清空了下，但好像还是没有问题。。好像也没有收到其他反馈，暂时只能咕咕了
