### ISSUE TITLE
首页推荐视频与插件视频挤在一起

### ISSUE THREAD

**Issue by noriole** [chitosai/bili-guessYouLike#8]
![Snipaste_2021-06-12_19-17-53](https://user-images.githubusercontent.com/62467022/121774124-51fc3600-cbb3-11eb-81f3-2e3c475a8ba1.png)
firefox nightly 91.0a1 (2021-06-11) (64 位)
win10

**Comment by chitosai** [comment]
哎呀。。这个问题真的每隔一段时间都要解释一遍，FF不是我发布的，你需要找一下FF插件的发布者，让他来合并我的最新代码重新发布就可以了

**Comment by niu541412** [comment]
已经更新。平常不怎么用Firefox，所以没留意bug
