### ISSUE TITLE
在新版网页失效了

### ISSUE THREAD

**Issue by sengluty198** [chitosai/bili-guessYouLike#9]
求适应新版网页界面

**Comment by chitosai** [comment]
等了好久，好像还是没灰度到我，暂时修不了啊

**Comment by chitosai** [comment]
首页的改版推送到我了，我今天修复了首页显示的部分，更新到1.13应该会恢复显示。

不过视频页我这边还没变，如果你们那边视频页也改版了的话可能会出现抓不到推荐视频的问题，这个得再等等看什么时候推送到我才能修
